### ISSUE TITLE
Not reading release-note block

### ISSUE THREAD

**Issue by kevinkirkup** [paultyng/changelog-gen#9]
When using the terraform-provider example changelog and release-note templates, it's not reading the release-notes block unless a variable is applied.

This uses the issue title:
\`\`\`release-notes
Blah
\`\`\`

This uses the block text
\`\`\`release-notes:
Some text
\`\`\`

**Comment by paultyng** [comment]
I think in this case the issue is plural `release-notes` vs `release-note`. I can add an `s` to the regex though.

**Comment by paultyng** [comment]
Fixed in 91f787dc0cf1eedf016a444740cd28a4f1370e4d

**Comment by kevinkirkup** [comment]
Thanks!

Still seeing the same issue with
\`\`\`release-note
\`\`\`

**Comment by kevinkirkup** [comment]
Here is the repo/branch I'm testing with:
https://github.com/pureport/terraform-provider-pureport/tree/feature/PE-2237_Automate_ChangeLog

envsetup.sh contains the function that I'm running:

```
  changelog-gen \
    -repo terraform-provider-pureport \
    -owner pureport \
    -branch develop \
    -changelog .ci/changelog.tmpl \
    -releasenote .ci/release-note.tmpl \
    -no-note-label "changelog: no-release-note" \
    3ea7eae2ac80e21b6190a2a6dcce15a74dd263f5 614ecfb172bd59abf00095a8c90a34e073530e9e
```

**Comment by paultyng** [comment]
Weird, there is a unit test in there testing that pattern. Is there a PR that it is not picking up? When I run this (with the default templates), this is what I get:

---
IMPROVEMENTS

* Automate CHANGELOG.md using paultyng/changelog-gen. ([40](https://github.com/pureport/terraform-provider-pureport/pull/40) by [kevinkirkup](https://github.com/kevinkirkup))
* Update Pureport SDK v2.0.0 ([34](https://github.com/pureport/terraform-provider-pureport/pull/34) by [kevinkirkup](https://github.com/kevinkirkup))
* [PE-2173] Update documentation to show ike_version as optional ([38](https://github.com/pureport/terraform-provider-pureport/pull/38) by [kevinkirkup](https://github.com/kevinkirkup))
* [PE-2210] Setup/Teardown environment for each test run ([39](https://github.com/pureport/terraform-provider-pureport/pull/39) by [kevinkirkup](https://github.com/kevinkirkup))

BUGS

* Set the default IKE Version to 'V2'. ([35](https://github.com/pureport/terraform-provider-pureport/pull/35) by [kevinkirkup](https://github.com/kevinkirkup))
* Update CloudServices acceptance tests based on new services. ([37](https://github.com/pureport/terraform-provider-pureport/pull/37) by [kevinkirkup](https://github.com/kevinkirkup))
* [PE-2149] Add custom validator for cloud connections for HA ([33](https://github.com/pureport/terraform-provider-pureport/pull/33) by [kevinkirkup](https://github.com/kevinkirkup))
